export interface DataMainFormObject {
    uid: string;
    idType: string;
    id: string;
    campusName: string;
    name: string;
    description: string;
    lastName: string;
    birthDate: string;
    age: string;
    phone: any;
    phone2: any;
    address: string;
    country: string;
    state: any;
    city: string;
    email: string;
    password: string;
    confirmPassword: string;
    cardNumber: string;
    medicalRecord: string;
    specialty: string;
    contract: string;
    rol: string;
    campus: string;
    area: string;
    urlPhoto: string;
    timestamp: any;
    isActive: any;
    isDeleted: boolean;
}

export type DataFunctionaryObject = {
    uid: string;
    idType: string;
    id: string;
    name: string;
    lastName: string;
    phone: any;
    email: string;
    password: string;
    confirmPassword: string;
    rol: string;
    campus: string;
    area: string;
    urlPhoto: string;
    timestamp: any;
    isActive: any;
};

export type DataPatientObject = {
    uid: string;
    idType: string;
    id: string;
    name: string;
    lastName: string;
    birthDate: string;
    age: string;
    phone: any;
    phone2: any;
    address: string;
    country: string;
    state: any;
    city: string;
    email: string;
    password: string;
    confirmPassword: string;
    rol: string;
    urlPhoto: string;
    timestamp: any;
    isActive: any;
};

export type DataProfessionalObject = {
    uid: string;
    idType: string;
    id: string;
    name: string;
    lastName: string;
    phone: any;
    phone2: any;
    address: string;
    country: string;
    state: any;
    city: string;
    email: string;
    password: string;
    confirmPassword: string;
    cardNumber: string;
    medicalRecord: string;
    specialty: string;
    contract: string;
    rol: string;
    urlPhoto: string;
    timestamp: any;
    isActive: any;
};

export type DataCampusObject = {
    uid: string;
    campusName: string;
    description: string;
    // phone: any;
    phone2: any;
    address: string;
    country: string;
    state: any;
    city: string;
    timestamp: any;
    isActive: any;
};
